from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import json
import os
import shutil
import pandas as pd
from typing import List, Dict, Any
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
import process # Import our logic from process.py
from dotenv import load_dotenv

# Load local environment variables if .env exists
load_dotenv()

app = FastAPI()

# Mount frontend build directory (created via npm run build)
frontend_dist = "frontend/dist"
if os.path.exists(frontend_dist):
    print(f"INFO: Serving frontend from {os.path.abspath(frontend_dist)}")
    app.mount("/assets", StaticFiles(directory=f"{frontend_dist}/assets"), name="assets")
else:
    print(f"WARNING: {frontend_dist} not found. Frontend will not be served!")

@app.get("/")
async def serve_index():
    if os.path.exists(f"{frontend_dist}/index.html"):
        return FileResponse(f"{frontend_dist}/index.html")
    return {"message": "Frontend not built. Please run 'npm run build' in the frontend directory."}

# Enable CORS for frontend development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Standardize path for Docker/Local flexibility
CATEGORIES_FILE = os.getenv("CATEGORIES_PATH", "categories.json")
CONFIG_FILE = os.getenv("CONFIG_PATH", "config.json")

@app.get("/api/categories")
async def get_categories():
    if not os.path.exists(CATEGORIES_FILE):
        return {"categories": []}
    with open(CATEGORIES_FILE, "r") as f:
        return json.load(f)

@app.post("/api/categories")
async def save_categories(data: Dict[str, Any]):
    with open(CATEGORIES_FILE, "w") as f:
        json.dump(data, f, indent=4)
    return {"status": "success"}

@app.get("/api/config")
async def get_config():
    default_config = {
        "debit_columns": ["Date", "Description", "Category", "Title", "Debit"],
        "credit_columns": ["Date", "Description", "Category", "Title", "Credit"],
        "duplicates_columns": ["Date", "Description", "Category", "Title", "Debit", "Credit"]
    }
    if not os.path.exists(CONFIG_FILE):
        return default_config
    with open(CONFIG_FILE, "r") as f:
        config = json.load(f)
        # Ensure new keys are present
        for k, v in default_config.items():
            if k not in config: config[k] = v
        return config

@app.post("/api/config")
async def save_config(data: Dict[str, Any]):
    with open(CONFIG_FILE, "w") as f:
        json.dump(data, f, indent=4)
    return {"status": "success"}

@app.post("/api/process")
async def process_statement(files: List[UploadFile] = File(...)):
    temp_inputs = []
    for file in files:
        temp_input = f"temp_{file.filename}"
        with open(temp_input, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        temp_inputs.append(temp_input)
    
    # We use the first filename as a base or just 'combined'
    output_base = "combined" if len(temp_inputs) > 1 else temp_inputs[0].replace(".csv", "")
    
    try:
        # results = debits + credits (categorized)
        results, unmatched, duplicates = process.process_csv(temp_inputs, output_base, CATEGORIES_FILE, CONFIG_FILE)
            
        return {
            "results": results,
            "unmatched": unmatched,
            "duplicates": duplicates
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        # Cleanup temp files
        for temp_input in temp_inputs:
            if os.path.exists(temp_input): os.remove(temp_input)
        
        # Also cleanup the actual .csv files generated by process_csv if any
        for suffix in ['.debit.csv', '.credit.csv', '.duplicates.csv', '.NO_CATEGORY.csv']:
            path = output_base + suffix
            if os.path.exists(path): os.remove(path)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
